In [27]:
import pandas as pd

In [31]:
rain = pd.read_csv("강수량_통계청_원본.csv")

In [32]:
rain.shape

(31, 13)

In [33]:
rain=rain[["시군구","2018_평균 강수량","2019_평균 강수량","2020_평균 강수량"]]

In [34]:
rain

     시군구  2018_평균 강수량  2019_평균 강수량  2020_평균 강수량
0    수원시   182.766667   125.866667   378.366667
1    성남시   212.500000   155.333333   365.500000
2    안양시   159.533333   157.000000   359.333333
3    부천시   199.533333   155.000000   307.500000
4    광명시   150.666667   149.666667   326.666667
5    평택시   214.166667   117.133333   361.233333
6    안산시   177.666667   127.666667   333.666667
7    과천시   178.333333   193.166667   388.666667
8    오산시   190.333333   135.166667   380.166667
9    시흥시   156.000000   125.800000   320.833333
10   군포시   136.000000   146.833333   360.500000
11   의왕시   190.800000   149.400000   305.733333
12   하남시   112.566667   200.000000   377.500000
13   용인시   206.933333   120.200000   401.000000
14   이천시   220.200000   125.366667   398.400000
15   안성시   193.566667   118.533333   381.900000
16   김포시   214.433333   106.700000   351.500000
17   화성시   157.600000   122.700000   336.066667
18   광주시   210.700000   173.533333   358.666667
19   여주시   209.566667   131.700000   382.033333
20   양평군   197.166667   154.866667   303.366667
21  의정부시   301.333333   175.500000   425.500000
22  동두천시   273.433333   176.100000   378.133333
23   고양시   312.666667   180.333333   349.000000
24   구리시   206.000000   181.933333   407.666667
25  남양주시   211.633333   187.333333   393.700000
26   파주시   221.833333   161.233333   335.366667
27   양주시   239.366667   154.300000   384.833333
28   포천시   251.666667   169.566667   357.066667
29   연천군   238.466667   162.600000   371.800000
30   가평군   221.733333   174.466667   382.500000

In [14]:
rain.to_csv("강수량_전처리.csv", index=False, encoding="utf-8-sig")